import express from "express";
import { config } from "dotenv";
import { GoogleSpreadsheet } from "google-spreadsheet";
import { JWT } from "google-auth-library";

config();

const app = express();
const port = process.env.PORT || 3000;

// // Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
// const serviceAccountAuth = new JWT({
//   // env var values here are copied from service account credentials generated by google
//   // see "Authentication" section in docs for more info
//   email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
//   key: process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, "\n"),
//   scopes: ["https://www.googleapis.com/auth/spreadsheets"],
// });

// const doc = new GoogleSpreadsheet(
//   "1Kji7K82Q-RvD29FXSigkaZseUBD8nufTyAWkG4PbprU",
//   serviceAccountAuth
// );

app.use(express.json());

app.post("/", async (req, res) => {
  const { data } = req.body;
  const user = data.users[1];
  const number = user.crm.tlf.number;

  try {
    // read/write row values
    res.status(200).json(number);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});
